// Generated by CoffeeScript 1.12.4
var assertValid, cloneObject, mergeDefaults;

assertValid = require("assertValid");

cloneObject = require("cloneObject");

mergeDefaults = function(obj, defaults) {
  var key, value;
  assertValid(obj, "object");
  assertValid(defaults, "object");
  for (key in defaults) {
    value = defaults[key];
    if (value && value.constructor === Object) {
      if (obj[key] === void 0) {
        obj[key] = cloneObject(value, true);
      } else if (obj[key] && obj[key].constructor === Object) {
        mergeDefaults(obj[key], value);
      }
    } else if (obj[key] === void 0) {
      obj[key] = value;
    }
  }
  return obj;
};

module.exports = mergeDefaults;
